### ISSUE TITLE
Undefined method `map`

### ISSUE THREAD

**Issue by ghost** [seamusabshere/fuzzy_match#23]
I am suddenly getting the following error when I attempt to create a new FuzzyMatch object with a global map of users as the object to search.
```ruby
`initialize': undefined method `map' for nil:NilClass (NoMethodError)
Did you mean?  tap
```
To create the new FuzzyMatch object I use the example:
```ruby
  def search_users(user)
    fz = FuzzyMatch.new(@user)
    project = fz.find(user)
    return user['id'], user['name']
  end
```
However the error only occurs after running the same search twice. If I search for user 'john' and then in the same query later search for a user 'john' it throws the error.

I am using Sinatra Version 3.6.2 and Ruby 2.3.1-p112

**Comment by rlue** [comment]
I'm not a maintainer of this project, but maybe I can help you suss out the problem. To be clear, `FuzzyMatch#new` takes an **array** of strings (the proverbial ‘haystack’), and `FuzzyMatch#find` takes a search query returns the **string value** of the best match (or ‘needle’) within the haystack.

Your method does the following:

1. accept a search query (`user`)
2. instantiate a new, one-element FuzzyMatch ‘haystack’ (`fz`),
3. find the search query's (`user`'s) best match within that ‘haystack’ (`project`)  
   (which is going to be `@user` if it's close, and `nil` if it's not), and then
5. return two values from the input parameter `user`.

Why do you create a `project` variable if you don't do anything with it? What exactly are you trying to capture in that variable, anyway? Just the string? The corresponding user object? 

***

Regarding your error, it's always good to include a backtrace, but it looks like what's happening is that the second time you call `search_users`, the `@user` instance variable is `nil`. The error gets thrown during the `initialize` method (_i.e.,_ `FuzzyMatch.new`), which is defined as follows:

``` ruby
def initialize(haystack, options_and_rules = {})
  # ... (setting options and rules)
  @haystack = haystack.map { |original| Record.new original, :stop_words => @stop_words, :read => @read }
end
```

`haystack.map` is what's throwing the error; the method is expecting an array, but getting `nil` instead.

**Comment by ghost** [comment]
I went over the code and as you mention the `@user` instance was nil. I completely overlooked it originally. Thanks for your help!
