### ISSUE TITLE
By default I get a 0.2 score match

### ISSUE THREAD

**Issue by priverop** [seamusabshere/fuzzy_match#31]
Hello!

I trying to use this gem to find similar Car Makes, but I'm getting a result I don't understand:

If I have the make Citroen and I look for the make "Volkswagen" I get the "Citroen" make:

FuzzyMatch.new(['Citroen']).find("Volkswagen") -> Citroen
FuzzyMatch.new(['Citroen']).find_with_score("Volkswagen") -> ["Citroen", 0.13333333333333333, 0.19999999999999996]

How is this possible? Am I doing something wrong? How can I change the threshold?

Thanks!

**Comment by gr8bit** [comment]
As far as I understand, it searches the best match from the given list. As you only have one entry in that list (Citroen), it's automatically picked as best match. Put all car brands in that first list and it will probably work as you expect.

**Comment by priverop** [comment]
That is correct. What was bothering me was getting 0.13 instead of nil or 0. But I guess the "-en" was giving that scoring. Thank you @gr8bit
